import { STUDIO_FILES } from '../../../analysis/studioPaths'
import { useStageOutputLoader } from '../../../hooks/useStageOutputLoader'
import { StudioEmpty, StudioSection } from '../StudioEmpty'
import { PrimaryValidationTrackContent } from './PrimaryValidationTrackSection'

/** Prominent boundary copy for /validation; compact=false for full page */
export function ValidationLoopBoundaryBanner() {
  return (
    <div
      className="rounded-xl border-2 border-slate-300 bg-slate-50 px-4 py-4 text-sm text-slate-800 leading-relaxed"
      role="region"
      aria-label="AI and human roles in validation"
    >
      <h2 className="text-xs font-bold uppercase tracking-wide text-slate-600 mb-2">AI / human boundary</h2>
      <ul className="list-disc pl-5 space-y-1.5 text-xs">
        <li>The analysis pipeline (AI-assisted) generated the broader candidate space and proposed validation branches.</li>
        <li>The researcher selects the concrete validation instance; without a saved selection file, that step is explicitly pending.</li>
        <li>The recipe is completed and refined within the selected validation branch — not as a global &quot;winner&quot; across all science.</li>
        <li>Experimental measurement adjudicates predictions; this UI does not substitute for lab results.</li>
      </ul>
    </div>
  )
}

const TAB_BOUNDARY_NOTE = (
  <p className="text-xs text-gray-600 bg-slate-100 border border-slate-200 rounded-lg p-3 leading-relaxed">
    <strong className="text-slate-900">AI / human boundary:</strong> Route hypotheses and pools are generated by the
    analysis pipeline (AI-assisted). The <em>validation instance</em> is chosen by the researcher unless a saved selection
    file exists. Final recipes are completed with AI assistance but must be reviewed in the lab. No single instance (e.g.
    lotus-root) is a &quot;global winner&quot; — it is one candidate in an explicit branch.
  </p>
)

function BroaderCandidateSpaceBody({ loading, result }) {
  if (loading) return <p className="text-xs text-gray-500">Loading…</p>
  if (result?.status !== 'ok') {
    return (
      <StudioEmpty
        title="Stage 3 branch outputs missing or unavailable"
        detail={result?.message || 'branch_selection.json was not found. Broader candidate space cannot be shown until Stage 3 Step A outputs are indexed.'}
      />
    )
  }
  const d = result.data
  const routes = d.evaluated_routes ?? d.routes ?? d.candidate_routes ?? d.list_1 ?? []
  const notStarchOnly =
    d.broader_space_note ?? d.why_not_starch_only ?? d.note_broader_than_starch ?? d.candidate_space_scope_note

  return (
    <div className="space-y-3 text-sm">
      <p className="text-xs text-gray-600">
        Evaluated routes enumerate the broader hypothesis space. The primary validation branch (section B) is one focused
        thread — not the entire scientific possibility set.
      </p>
      {notStarchOnly && (
        <p className="text-xs text-violet-900 bg-violet-50 border border-violet-100 rounded-lg p-2">
          <span className="font-semibold">Broader space ≠ starch-only:</span>{' '}
          {typeof notStarchOnly === 'string' ? notStarchOnly : JSON.stringify(notStarchOnly)}
        </p>
      )}
      <div>
        <h4 className="text-xs font-semibold text-gray-700 mb-1">Evaluated routes</h4>
        {Array.isArray(routes) && routes.length > 0 ? (
          <ul className="text-xs space-y-1 max-h-48 overflow-auto border rounded p-2 bg-gray-50">
            {routes.slice(0, 40).map((r, i) => (
              <li key={i} className="font-mono truncate" title={JSON.stringify(r)}>
                {r.route_id ?? r.id ?? r.name ?? r.subfamily_id ?? JSON.stringify(r).slice(0, 120)}
              </li>
            ))}
            {routes.length > 40 && <li className="text-gray-500">…and {routes.length - 40} more</li>}
          </ul>
        ) : (
          <pre className="text-xs bg-gray-50 p-2 rounded max-h-40 overflow-auto whitespace-pre-wrap">{JSON.stringify(d, null, 2)}</pre>
        )}
      </div>
    </div>
  )
}

function PrimaryBranchHighlight({ selected }) {
  if (selected == null) return null
  return (
    <div className="rounded-lg border-2 border-blue-200 bg-blue-50/40 p-3 mt-2">
      <h4 className="text-xs font-semibold text-blue-900">Primary validation branch (from branch_selection.json)</h4>
      <pre className="text-[11px] mt-1 whitespace-pre-wrap font-sans">{typeof selected === 'string' ? selected : JSON.stringify(selected, null, 2)}</pre>
    </div>
  )
}

/** Sections A + B with a single branch_selection.json load */
export function ValidationLoopBranchSections() {
  const { loading, result } = useStageOutputLoader(STUDIO_FILES.branchSelection, { kindHint: 'json' })
  const selected = result?.status === 'ok' ? (result.data.primary_validation_branch ?? result.data.selected_branch ?? result.data.chosen_route ?? result.data.primary_branch) : null

  return (
    <>
      <StudioSection title="A. Broader Candidate Space" subtitle="branch_selection.json — evaluated routes">
        <BroaderCandidateSpaceBody loading={loading} result={result} />
      </StudioSection>
      <StudioSection
        title="B. Primary Validation Branch"
        subtitle="Why this branch is the main validation thread (not the only valid scientific route)"
      >
        <PrimaryValidationBranchPanel branchLoading={loading} branchResult={result} selected={selected} />
      </StudioSection>
    </>
  )
}

function PrimaryValidationBranchPanel({ branchLoading, branchResult, selected }) {
  const { loading: trackLoading, result: trackResult } = useStageOutputLoader(STUDIO_FILES.primaryValidationTrack, {
    kindHint: 'json',
  })

  if (branchLoading || trackLoading) return <p className="text-xs text-gray-500">Loading…</p>

  if (trackResult?.status === 'ok') {
    return (
      <div className="space-y-3">
        <p className="text-xs text-gray-600">
          Structured narrative from <code className="text-[10px] bg-gray-100 px-1 rounded">primary_validation_track.json</code>.
          Use together with the highlighted branch object in <code className="text-[10px] bg-gray-100 px-1 rounded">branch_selection.json</code>.
        </p>
        <PrimaryValidationTrackContent d={trackResult.data} />
        <PrimaryBranchHighlight selected={selected} />
      </div>
    )
  }

  if (branchResult?.status === 'ok') {
    const d = branchResult.data
    const reason = d.selection_reason ?? d.primary_branch_rationale ?? d.why_primary_branch
    const mech = d.mechanism_discrimination_value ?? d.mechanism_probe_value ?? d.route_role
    return (
      <div className="space-y-3 text-sm">
        <p className="text-xs text-amber-800 bg-amber-50 border border-amber-100 rounded-lg p-2">
          <code className="text-[10px]">primary_validation_track.json</code> unavailable — showing fields inferred from{' '}
          <code className="text-[10px]">branch_selection.json</code> only.
        </p>
        {reason && (
          <p className="text-xs">
            <span className="font-semibold">Selection reason:</span>{' '}
            {typeof reason === 'string' ? reason : JSON.stringify(reason)}
          </p>
        )}
        {mech != null && (
          <p className="text-xs">
            <span className="font-semibold">Mechanism discrimination / route role:</span>{' '}
            {typeof mech === 'object' ? JSON.stringify(mech) : String(mech)}
          </p>
        )}
        <PrimaryBranchHighlight selected={selected} />
        {!reason && mech == null && selected == null && (
          <pre className="text-xs bg-gray-50 p-2 rounded whitespace-pre-wrap max-h-56 overflow-auto">{JSON.stringify(d, null, 2)}</pre>
        )}
        <p className="text-[11px] text-gray-500">
          This is the primary validation thread for the current design, not a claim that all other routes are invalid.
        </p>
      </div>
    )
  }

  return (
    <StudioEmpty
      title="Primary validation branch unavailable"
      detail={trackResult?.message || branchResult?.message || 'Need branch_selection.json or primary_validation_track.json.'}
    />
  )
}

export function RoutePoolBlock() {
  const { loading, result } = useStageOutputLoader(STUDIO_FILES.routeInstancePool, { kindHint: 'json' })
  if (loading) return <p className="text-xs text-gray-500">Loading…</p>
  if (result?.status !== 'ok') {
    return (
      <StudioEmpty
        title="route_instance_pool.json unavailable"
        detail={result?.message || 'AI-generated route instance pool not indexed.'}
      />
    )
  }
  const d = result.data
  const instances = d.instances ?? d.instance_pool ?? d.pool ?? (Array.isArray(d) ? d : [])

  return (
    <div className="space-y-2">
      <p className="text-xs text-gray-600">
        Concrete host instances listed here are options in the AI-generated pool — not a ranked universal winner list.
      </p>
      <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
        {(Array.isArray(instances) ? instances : []).map((inst, i) => (
          <li key={i} className="border rounded-lg p-2 bg-white">
            <span className="font-semibold">{inst.name ?? inst.instance_name ?? inst.host_label ?? inst.id ?? `Instance ${i + 1}`}</span>
            {inst.suitability_score != null && (
              <span className="block text-gray-500 mt-0.5">Suitability: {inst.suitability_score}</span>
            )}
            {inst.notes && <span className="block text-gray-600 mt-1">{inst.notes}</span>}
          </li>
        ))}
      </ul>
      {!Array.isArray(instances) || instances.length === 0 ? (
        <pre className="text-xs bg-gray-50 p-2 rounded whitespace-pre-wrap max-h-40 overflow-auto">{JSON.stringify(d, null, 2)}</pre>
      ) : null}
    </div>
  )
}

export function ResearcherSelectionBlock() {
  const { loading, result } = useStageOutputLoader(STUDIO_FILES.researcherMaterialSelection, { kindHint: 'json' })

  if (loading) return <p className="text-xs text-gray-500">Loading…</p>

  if (!result || result.status !== 'ok') {
    return (
      <div className="rounded-lg border border-dashed border-amber-300 bg-amber-50/50 p-4 text-sm text-gray-700 space-y-2">
        <p className="font-semibold text-amber-900">Awaiting researcher selection</p>
        <p className="text-xs">
          <code className="text-[10px] bg-white/80 px-1 rounded">researcher_material_selection.json</code> was not found.
          The concrete validation instance is a human boundary: record your choice in the pipeline to populate this block.
        </p>
        <p className="text-xs text-gray-600">
          Template: once the file exists, this section will show an explicit <strong>Human-selected validation instance</strong>{' '}
          label and the saved JSON.
        </p>
      </div>
    )
  }

  const d = result.data
  return (
    <div className="rounded-lg border-2 border-emerald-300 bg-emerald-50/40 p-4 space-y-2">
      <p className="text-sm font-bold text-emerald-900">Human-selected validation instance</p>
      <p className="text-xs text-emerald-900/90">
        This selection is distinct from AI-generated route lists above. It marks the researcher-chosen instance for lab
        validation.
      </p>
      <pre className="text-xs whitespace-pre-wrap font-sans max-h-60 overflow-auto">{JSON.stringify(d, null, 2)}</pre>
    </div>
  )
}

export function ValidationRecipeBlock() {
  const recipe = useStageOutputLoader(STUDIO_FILES.validationRecipeSpace, { kindHint: 'json' })
  const stab = useStageOutputLoader(STUDIO_FILES.researchPriorityRankStability, { kindHint: 'json' })
  const top10 = useStageOutputLoader(STUDIO_FILES.researchPriorityTop10, { kindHint: 'json' })

  if (recipe.loading) return <p className="text-xs text-gray-500">Loading…</p>
  if (recipe.result?.status !== 'ok') {
    return (
      <StudioEmpty
        title="validation_recipe_space.json unavailable"
        detail="Recipe space is produced within the selected validation branch. If this file is missing, Stage B recipe completion may not have run yet."
      />
    )
  }

  const d = recipe.result.data
  const selected = d.selected_recipe ?? d.recipe ?? d.primary_recipe ?? d
  const modules = d.modules ?? d.recipe_modules ?? selected?.modules
  const rationale = d.rationale ?? d.selection_rationale ?? selected?.rationale ?? d.why_this_recipe
  const rankStab = stab.result?.status === 'ok' ? stab.result.data : null
  const topOk = top10.result?.status === 'ok' ? top10.result.data : null
  const topCount = topOk
    ? Array.isArray(topOk.candidates)
      ? topOk.candidates.length
      : Array.isArray(topOk.top_10)
        ? topOk.top_10.length
        : Array.isArray(topOk)
          ? topOk.length
          : null
    : null

  return (
    <div className="space-y-3 text-sm">
      <p className="text-xs text-gray-600">
        Recipe content is scoped to the selected validation branch. It is not presented as a cross-study &quot;AI global
        winner&quot;.
      </p>
      <div className="rounded-lg border p-3 bg-white">
        <h4 className="text-xs font-semibold text-gray-800">Recipe within branch</h4>
        <pre className="text-xs mt-2 whitespace-pre-wrap max-h-56 overflow-auto font-sans">{typeof selected === 'string' ? selected : JSON.stringify(selected, null, 2)}</pre>
      </div>
      {modules && (
        <div>
          <h4 className="text-xs font-semibold mb-1">Modules</h4>
          <pre className="text-xs bg-gray-50 p-2 rounded whitespace-pre-wrap max-h-40 overflow-auto">{JSON.stringify(modules, null, 2)}</pre>
        </div>
      )}
      {rationale && (
        <p className="text-xs text-gray-700">
          <span className="font-semibold">Why this recipe (in-branch):</span>{' '}
          {typeof rationale === 'string' ? rationale : JSON.stringify(rationale)}
        </p>
      )}
      {rankStab && (
        <details className="text-xs border rounded p-2">
          <summary className="cursor-pointer font-semibold">Rank stability (research_priority_rank_stability.json)</summary>
          <pre className="mt-2 max-h-36 overflow-auto whitespace-pre-wrap">{JSON.stringify(rankStab, null, 2)}</pre>
        </details>
      )}
      {topCount != null && (
        <p className="text-[11px] text-gray-500">
          Optional cross-check: <code className="text-[10px] bg-gray-100 px-1 rounded">research_priority_top10_candidates.json</code>{' '}
          lists {topCount} ranked row(s) in the current file snapshot (for context, not a performance leaderboard).
        </p>
      )}
    </div>
  )
}

/** Combined branch UI for Analysis → Validation tab (single section, original layout) */
export function BranchSelectionBlock() {
  const { loading, result } = useStageOutputLoader(STUDIO_FILES.branchSelection, { kindHint: 'json' })
  if (loading) return <p className="text-xs text-gray-500">Loading…</p>
  if (result?.status !== 'ok') {
    return <StudioEmpty title="branch_selection.json unavailable" detail={result?.message} />
  }
  const d = result.data
  const routes = d.evaluated_routes ?? d.routes ?? d.candidate_routes ?? d.list_1 ?? []
  const selected = d.primary_validation_branch ?? d.selected_branch ?? d.chosen_route ?? d.primary_branch

  return (
    <div className="space-y-3 text-sm">
      <div>
        <h4 className="text-xs font-semibold text-gray-700 mb-1">Evaluated routes (broader candidate space)</h4>
        {Array.isArray(routes) && routes.length > 0 ? (
          <ul className="text-xs space-y-1 max-h-48 overflow-auto border rounded p-2 bg-gray-50">
            {routes.slice(0, 40).map((r, i) => (
              <li key={i} className="font-mono truncate" title={JSON.stringify(r)}>
                {r.route_id ?? r.id ?? r.name ?? r.subfamily_id ?? JSON.stringify(r).slice(0, 120)}
              </li>
            ))}
            {routes.length > 40 && <li className="text-gray-500">…and {routes.length - 40} more</li>}
          </ul>
        ) : (
          <pre className="text-xs bg-gray-50 p-2 rounded max-h-40 overflow-auto whitespace-pre-wrap">{JSON.stringify(d, null, 2)}</pre>
        )}
      </div>
      {selected != null && (
        <div className="rounded-lg border-2 border-blue-200 bg-blue-50/40 p-3">
          <h4 className="text-xs font-semibold text-blue-900">Selected primary validation branch</h4>
          <pre className="text-[11px] mt-1 whitespace-pre-wrap font-sans">{typeof selected === 'string' ? selected : JSON.stringify(selected, null, 2)}</pre>
        </div>
      )}
    </div>
  )
}

export { TAB_BOUNDARY_NOTE }
