import { Link } from 'react-router-dom'
import { StudioSection } from './StudioEmpty'
import {
  BranchSelectionBlock,
  ResearcherSelectionBlock,
  RoutePoolBlock,
  TAB_BOUNDARY_NOTE,
  ValidationRecipeBlock,
} from './validationLoop/ValidationLoopSections'

export function ValidationTab() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
        <p className="text-xs text-gray-500">File-backed validation blocks — same loaders as the Validation Loop page.</p>
        <Link
          to="/validation"
          className="text-sm font-medium text-indigo-600 hover:text-indigo-800 hover:underline shrink-0"
        >
          Open full Validation Loop →
        </Link>
      </div>
      {TAB_BOUNDARY_NOTE}
      <StudioSection title="Broader candidate space & branch selection" subtitle="branch_selection.json">
        <BranchSelectionBlock />
      </StudioSection>
      <StudioSection title="Route instance pool" subtitle="route_instance_pool.json">
        <RoutePoolBlock />
      </StudioSection>
      <StudioSection title="Researcher selection" subtitle="researcher_material_selection.json">
        <ResearcherSelectionBlock />
      </StudioSection>
      <StudioSection title="Validation recipe space" subtitle="validation_recipe_space.json (+ optional rank stability)">
        <ValidationRecipeBlock />
      </StudioSection>
      <p className="text-[11px] text-gray-500 px-1">
        Flow: routes generated by the AI-assisted pipeline → instance selected by the researcher → recipe documented with AI
        assistance for lab follow-up.
      </p>
    </div>
  )
}
